Repository DemocracyLab/CivicTechExchange, pull requests merged in 2020-03, with the labels that each got.

#341 Peter/home moreprojects
  civictechprojects/static/css/partials/_LandingController.scss
  common/components/componentsBySection/Landing/RecentProjectsSection.jsx
  common/components/utils/glyphs.js
Labels: javascript, ready for review

#342 New user option to sign up for DemocracyLab Newsletter
  common/components/controllers/SignUpController.jsx
  common/helpers/front_end.py
  common/helpers/mailing_list.py
  democracylab/settings.py
  democracylab/urls.py
  democracylab/views.py
  democracylab_environment_variables.sh
  requirements.txt
Labels: ready for review

#343 OAuth login links re-skin
  civictechprojects/static/css/partials/_LogInController.scss
  common/components/common/integrations/SocialMediaSignupSection.jsx
  common/components/svg/facebook.svg
  common/components/svg/github.svg
  common/components/svg/google.svg
  common/components/svg/linkedin.svg
  common/components/test/utils.test.js
  common/components/utils/svg.js
Labels: ready for review

#345 2020-03-06 Release Fixes
  civictechprojects/views.py
  common/components/componentsBySection/Landing/RecentProjectsSection.jsx
  common/components/forms/LinkEntryModal.jsx
Labels: ready for review

#347 Add Docker build flow
  .dockerignore
  .gitignore
  Dockerfile
  civictechprojects/forms.py
  civictechprojects/sitemaps.py
  civictechprojects/views.py
  common/fixtures/testdata readme.txt
  common/fixtures/testdata.json
  common/helpers/caching.py
  common/tests/test_helpers.py
  democracylab/settings.py
  democracylab_environment_variables.sh
  docker-compose.yml
  requirements.txt
Labels: ready for review

#349 Testimonial update
  common/components/componentsBySection/Landing/Testimonials.jsx
Labels: in progress

#350 Single Project Card layout
  civictechprojects/static/css/partials/_LandingController.scss
  civictechprojects/static/css/partials/_ProjectCard.scss
Labels: in progress

#339 Build flow: Build Sass files using webpack's plugin And Add run watch command
  .gitignore
  civictechprojects/templates/new_index.html
  package.json
  webpack.config.js
  yarn.lock
Labels: needs regression testing

#353 About Us Page fixes
  Dockerfile
  common/components/controllers/AboutUsController.jsx
  common/fixtures/testdata readme.txt
  common/fixtures/testdata.json
  democracylab_environment_variables.sh
Labels: ready for review

#346 Build flow: Use terser plugin to minify prod build size
  .gitignore
  civictechprojects/templates/new_index.html
  package.json
  webpack.common.js
  webpack.config.js
  webpack.dev.js
  webpack.prod.js
  yarn.lock
Labels: needs regression testing
