Repository DemocracyLab/CivicTechExchange, pull requests merged in 2020-02, with the labels that each got.

#326 Add Board of Directors to About Us Page
  civictechprojects/models.py
  civictechprojects/static/css/partials/_LogInController.scss
  civictechprojects/static/css/partials/_SignUpController.scss
  civictechprojects/static/css/styles.scss
  civictechprojects/urls.py
  civictechprojects/views.py
  common/components/componentsBySection/AboutUs/BioModal.jsx
  common/components/componentsBySection/AboutUs/BioPersonData.jsx
  common/components/componentsBySection/AboutUs/BioThumbnail.jsx
  common/components/controllers/AboutUsController.jsx
  common/components/controllers/SignUpController.jsx
  common/components/test/utils.test.js
  common/components/utils/ProjectAPIUtils.js
  common/components/utils/groupBy.js
  democracylab/settings.py
  democracylab_environment_variables.sh
Labels: ready for review

#331 Make favicon configurable
  civictechprojects/templates/new_index.html
  civictechprojects/views.py
  democracylab/settings.py
  democracylab_environment_variables.sh
Labels: ready for review

#329 Add Volunteering terms to Sign Up page
  civictechprojects/static/css/partials/_SignUpController.scss
  common/components/chrome/PseudoLink.jsx
  common/components/common/confirmation/TermsModal.jsx
  common/components/common/notification/NotificationModal.jsx
  common/components/controllers/SignUpController.jsx
  common/models/Tag_definitions.csv
Labels: ready for review

#330 About Us Page Enhancements
  civictechprojects/models.py
  common/components/chrome/AlertHeader.jsx
  common/components/componentsBySection/AboutUs/BioModal.jsx
  common/components/controllers/AboutUsController.jsx
  common/components/utils/ProjectAPIUtils.js
  common/components/utils/utils.js
  democracylab_environment_variables.sh
Labels: ready for review

#327 New landing page
  civictechprojects/static/css/_bootstrapoverride.scss
  civictechprojects/static/css/partials/_LandingController.scss
  civictechprojects/static/css/partials/_ProjectCard.scss
  civictechprojects/static/css/styles.scss
  civictechprojects/urls.py
  civictechprojects/views.py
  common/components/chrome/MainFooter.jsx
  common/components/chrome/MainHeader.jsx
  common/components/componentsBySection/FindProjects/ProjectCard.jsx
  common/components/componentsBySection/FindProjects/ProjectCardsContainer.jsx
  common/components/componentsBySection/FindProjects/SplashScreen.jsx
  common/components/componentsBySection/Landing/Partners.jsx
  common/components/componentsBySection/Landing/RecentProjectsSection.jsx
  common/components/componentsBySection/Landing/TestimonialCarousel.jsx
  common/components/componentsBySection/Landing/Testimonials.jsx
  common/components/controllers/FindProjectsController.jsx
  common/components/controllers/LandingController.jsx
  common/components/controllers/SectionController.jsx
  common/components/enums/Section.js
  common/components/svg/arrowright-black.svg
  common/components/svg/arrowright-orange.svg
  common/components/svg/recruit1.svg
  common/components/svg/recruit2.svg
  common/components/svg/recruit3.svg
  common/components/svg/volunteer1.svg
  common/components/svg/volunteer2.svg
  common/components/svg/volunteer3.svg
  democracylab/urls.py
  package.json
  webpack.config.js
  yarn.lock
Labels: javascript, python, ready for review

#334 Sitemap: Add Home page and remove Find Projects splash page
  civictechprojects/sitemaps.py
  common/components/enums/Section.js
  common/helpers/constants.py
Labels: ready for review

#336 2/21/2020 Release Bugfixes
  civictechprojects/static/css/partials/_ProjectCard.scss
  common/components/common/notification/NotificationModal.jsx
  common/components/controllers/SignUpController.jsx
Labels: javascript, ready for review
